language: node_js
node_js:
  - "node"
script:
  - "npm install -g pxt"
  - "pxt target microbit"
  - "pxt install"
  - "pxt build"
os: linux
dist: xenial
cache:
  directories:
    - npm_modules
    - pxt_modules
